### PR TITLE
Use mdpo to translate documentation

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@rffontenelle I moved this here just discuss a few issues:

* First, there's another distribution issue, mdpo does not provide arm specific packages for Linux and to rebuild those it requires the Rust compile :facepalm: . Similar as with the other tool we tried, I don't think it's worth it to make the build environment that complex. There might be other solutions like providing dist packages that are built on supported architectures but that's a some extra work as well.
* Second, I integrated the steps of your script to meson (which answers your previous question), but not everything will work out as expected, e.g., `msgmerge` doesn't support multiple PO files and meson `run_target` can't run more than one command. Therefore, for this to work on multiple platforms that script would need to be broken down into separate tools (e..g, under `docs/tools`) and rewritten in Python.

**Comment by rffontenelle** [comment]
>     * First, there's another distribution issue, mdpo does not provide arm specific packages for Linux and to rebuild those it requires the Rust compiler 🤦 . Similar as with the other tool we tried, I don't think it's worth it to make the build environment that complex. There might be other solutions like providing dist packages that are built on supported architectures but that's a some extra work as well.

Do you know if Sphinx have ARM specific packages? I seems to [support Markdown files](https://github.com/sphinx-doc/sphinx) and with a proper conf.py configuration file and we have most job done, although building different languages need to be a separate run (e.g. "-Dlanguages=pt_BR", "-Dlanguages=es", etc.)

>     * Second, I integrated the steps of your script to meson (which answers your previous question), but not everything will work out as expected, e.g., `msgmerge` doesn't support multiple PO files and meson `run_target` can't run more than one command. Therefore, for this to work on multiple platforms that script would need to be broken down into separate tools (e..g, under `docs/tools`) and rewritten in Python.

So, one script for generating POT and updating PO files, and other script for generating the translated Markdown from PO files. Right?

**Comment by tchx84** [comment]
> 
> Do you know if Sphinx have ARM specific packages? 

Not sure, but I can check.

I seems to [support Markdown files](https://www.sphinx-doc.org/en/master/usage/markdown.html) and with a proper conf.py configuration file and we have most job done, although building different languages need to be a separate run (e.g. "-Dlanguages=pt_BR", "-Dlanguages=es", etc.)

Interesting, have you tried this particular feature before? I have used Sphinx before, but haven't checked the i18n support.

> 
> So, one script for generating POT and updating PO files, and other script for generating the translated Markdown from PO files. Right?

Yes. But you could break down the first one in two as well, e.g., so we would have something similar to regular `ninja gameeky-pot` and `ninja gameeky-update-po`.

**Comment by rffontenelle** [comment]
> Interesting, have you tried this particular feature before? I have used Sphinx before, but haven't checked the i18n support.

It is not exactly a feature. If you run sphinx-build (with usual parameters) it will only build English (or whatever source language is set in conf.py). To build other [languages](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language), one must pass `-D language=$LANG` so that, combined with [locale_dirs](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-locale_dirs) conf passed in CLI or set in conf.py, it looks for the PO file and build translated doc. Sphinx doesn't build multiple languages at once, see https://github.com/sphinx-doc/sphinx/issues/11713

See [Internationalization](https://www.sphinx-doc.org/pt-br/master/usage/advanced/intl.html) in Sphinx docs for more info.

(In my previous message I wrote incorrectly the flag 'language' as 'languages' (plural), and that's a invalid conf. Fixed now)

> 
> Yes. But you could break down the first one in two as well, e.g., so we would have something similar to regular `ninja gameeky-pot` and `ninja gameeky-update-po`.

Got it.

**Comment by rffontenelle** [comment]
Uploading the scripts, as I don't have commit permissions to your merge request (appended '.txt' to be able to upload):

- [update_po.py](https://github.com/tchx84/Gameeky/files/14878678/update_po.py.txt)
- [generate_pot.py](https://github.com/tchx84/Gameeky/files/14878679/generate_pot.py.txt)
- [build_md.py](https://github.com/tchx84/Gameeky/files/14878680/build_md.py.txt)

**Comment by tchx84** [comment]
@rffontenelle create a new branch off this branch :) and send a new PR

**Pull request closed without merging**
