### PR TITLE
Initial Hindi translation

### PR DESCRIPTION
**Pull request by Scrambled777**
Adds initial Hindi `hi` translation for the app and documentation.

### CODE REVIEW

**Comment by Scrambled777** [comment]
Closed it accidentally. Opening again.

**Comment by rffontenelle** [comment]
Would you consider translation docs as well? Please see [docs/README.md](https://github.com/tchx84/Gameeky/blob/main/doc/README.md)

**Comment by Scrambled777** [comment]
> Would you consider translating docs as well? Please see [docs/README.md](https://github.com/tchx84/Gameeky/blob/main/docs%2FREADME.md)

Somehow I missed that readme doc when I opened PR initially.

I have already translated `docs/basics/po/hi.po`. Will checkout those commands. 

Is it alright to ask question here, if I get stuck? I don't do well in command line.

**Comment by Scrambled777** [comment]
@rffontenelle 

I'm stuck in `pip install --user mdpo`. 

<details>

<summary>Error Output</summary>

```bash
pip install --user mdpo
Collecting mdpo
  Using cached mdpo-2.0.1-py3-none-any.whl.metadata (3.2 kB)
Collecting contextlib-chdir<2,>=1 (from mdpo)
  Using cached contextlib_chdir-1.0.2-py3-none-any.whl.metadata (1.2 kB)
Collecting importlib-metadata-argparse-version<3,>=2 (from mdpo)
  Using cached importlib_metadata_argparse_version-2.0.0-py3-none-any.whl.metadata (5.3 kB)
Collecting md-ulb-pwrap<1,>=0.1 (from mdpo)
  Using cached md_ulb_pwrap-0.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.9 kB)
Collecting polib<2,>=1.1 (from mdpo)
  Using cached polib-1.2.0-py2.py3-none-any.whl.metadata (15 kB)
Collecting pymd4c<2,>=1.3 (from mdpo)
  Using cached pymd4c-1.3.0.tar.gz (51 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-pbzc85_p/pymd4c.egg-info
      writing /tmp/pip-modern-metadata-pbzc85_p/pymd4c.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-pbzc85_p/pymd4c.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-modern-metadata-pbzc85_p/pymd4c.egg-info/requires.txt
      Traceback (most recent call last):
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 117, in <module>
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/command/dist_info.py", line 92, in run
          self.egg_info.run()
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 314, in run
          writer(self, ep.name, os.path.join(self.egg_info, ep.name))
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 702, in write_toplevel_names
          pkgs = dict.fromkeys([
                               ^
        File "/tmp/pip-build-env-z3cq76wu/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 925, in iter_distribution_names
          for ext in self.ext_modules or ():
        File "<string>", line 61, in __iter__
        File "<string>", line 55, in _fetch_pkgconfig_all
        File "<string>", line 38, in _fetch_pkgconfig
        File "/tmp/pip-build-env-z3cq76wu/normal/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 248, in parse
          _raise_if_not_exists(package)
        File "/tmp/pip-build-env-z3cq76wu/normal/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 103, in _raise_if_not_exists
          raise PackageNotFoundError(package)
      pkgconfig.pkgconfig.PackageNotFoundError: md4c not found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```


</details>

I also installed `md4c` with this command `pip install --user md4c`. Still, I'm getting above error while running `pip install --user mdpo`.

I must admit that this is well beyond my knowledge area so, I need assistance. 

Cheers.

**Comment by rffontenelle** [comment]
@Scrambled777 Please try to install "md4c" (not with pip, as it is not a Python package). If on Linux, check [repology](https://repology.org/project/md4c/versions) for availability on distros.

**Comment by Scrambled777** [comment]
@rffontenelle 

Thanks for the assistance. 

For `pip install --user mdpo` command to work on Fedora 40, I had to install `python3-devel` in addition to `md4c`.

It would be appreciate if you could also mention these extra packages also under `Requirements` section of `docs/README.md`

Now, I have also included translated html & md file.

Kindly verify if it meets your requirement.

Cheers.

**Comment by rffontenelle** [comment]
Thanks for your contribution. Here are some feedbacks:
- Make sure to translate the link fragments in Topics (the summary of sections in the beginning of the page) to match the translated heading text. For instance: you translated "introduction" to "परिचय", so the Topics entry should say `[परिचय](#परिचय)` instead of `[परिचय](#introduction)`.
- Please remove the src/hi/index.md. We are only keeping the po and the html, but the intermediary md file we are not keeping in the Git tree. The translation instructions is missing this information, sorry about that.
- Make sure translation of the terms are the same in UI and docs. I haven't read your translation as I don't speak Hindi, but this just a friendly reminder.

**Comment by tchx84** [comment]
@Scrambled777 @rffontenelle I couldn't push some fixes myself here, so I am moving this to https://github.com/tchx84/Gameeky/pull/138

**Pull request closed without merging**
