### PR TITLE
Fix typo in Brazilian Portuguese documentation

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@rffontenelle FYI

**Comment by rffontenelle** [comment]
It seems we need a markdown linter of some sort to spot these issues earlier on pre-commit or pre-merge.

**Comment by tchx84** [comment]
> It seems we need a markdown linter of some sort to spot these issues earlier on pre-commit or pre-merge.

I haven't really used a MD linter before, but found this https://github.com/markdownlint/markdownlint

**Comment by rffontenelle** [comment]
I've used https://github.com/igorshubovych/markdownlint-cli, and I don't remember why not markdownlint. But we can try them. Would you prefer add as [pre-commit](https://pre-commit.com/) or github actions on push / pull_request events ?

**Comment by tchx84** [comment]
> I've used https://github.com/igorshubovych/markdownlint-cli, and I don't remember why not markdownlint. But we can try them. Would you prefer add as [pre-commit](https://pre-commit.com/) or github actions on push / pull_request events ?

We don't include the markdown files in the git repo, so neither would work. But we can suggest that step in https://github.com/tchx84/Gameeky/pull/129

**Comment by tchx84** [comment]
> > I've used https://github.com/igorshubovych/markdownlint-cli, and I don't remember why not markdownlint. But we can try them. Would you prefer add as [pre-commit](https://pre-commit.com/) or github actions on push / pull_request events ?
> 
> We don't include the markdown files in the git repo, so neither would work. But we can suggest that step in #129

Regarding the tool, let's use whatever you're familiar with.

**Pull request merged**
