### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by rffontenelle**

### CODE REVIEW

**Comment by tchx84** [comment]
@rffontenelle is this ready ?

**Comment by rffontenelle** [comment]
Let me just to update after the "front" fix.

**Comment by tchx84** [comment]
> Let me just to update after the "front" fix.

are you going to include an update to the .pot file here or should I do it in another PR?

**Comment by rffontenelle** [comment]
Feel free to update yourself. Away from keyboard now

**Comment by tchx84** [comment]
> Feel free to update yourself. Away from keyboard now

done, please rebase :+1:

**Comment by rffontenelle** [comment]
@tchx84 Translation updated and ready.

However I noticed that the HTML I generated has a small difference from yours. It means my pt_BR HTML was generated differently from your en and es.

See the unstaged/uncommitted git-diff from en and es HTML files.

Is this a problem?

```diff
diff --git a/docs/basics/html/en/index.html b/docs/basics/html/en/index.html
index 0e4fba5..7109edb 100644
--- a/docs/basics/html/en/index.html
+++ b/docs/basics/html/en/index.html
@@ -23,7 +23,7 @@
     .display.math{display: block; text-align: center; margin: 0.5rem auto;}
     /* CSS for syntax highlighting */
     pre > code.sourceCode { white-space: pre; position: relative; }
-    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
+    pre > code.sourceCode > span { line-height: 1.25; }
     pre > code.sourceCode > span:empty { height: 1.2em; }
     .sourceCode { overflow: visible; }
     code.sourceCode > span { color: inherit; text-decoration: inherit; }
@@ -34,7 +34,7 @@
     }
     @media print {
     pre > code.sourceCode { white-space: pre-wrap; }
-    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
+    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
     }
     pre.numberSource code
       { counter-reset: source-line 0; }
diff --git a/docs/basics/html/es/index.html b/docs/basics/html/es/index.html
index ac21281..8924b9c 100644
--- a/docs/basics/html/es/index.html
+++ b/docs/basics/html/es/index.html
@@ -23,7 +23,7 @@
     .display.math{display: block; text-align: center; margin: 0.5rem auto;}
     /* CSS for syntax highlighting */
     pre > code.sourceCode { white-space: pre; position: relative; }
-    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
+    pre > code.sourceCode > span { line-height: 1.25; }
     pre > code.sourceCode > span:empty { height: 1.2em; }
     .sourceCode { overflow: visible; }
     code.sourceCode > span { color: inherit; text-decoration: inherit; }
@@ -34,7 +34,7 @@
     }
     @media print {
     pre > code.sourceCode { white-space: pre-wrap; }
-    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
+    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
     }
     pre.numberSource code
       { counter-reset: source-line 0; }

```

**Comment by rffontenelle** [comment]
> Let me try locally, what version of pandoc are you using?

3.1.8

**Comment by tchx84** [comment]
@rffontenelle I suspect it's an artifact of using two different pandoc versions... it should be harmless, but for now I just added one commit here to make it all the same.

**Review by tchx84 — APPROVED** [review]

**Comment by tchx84** [comment]
Finally ! :tada:

**Pull request merged**
